import {
  Bell,
  Server,
  Users,
  Database,
  Globe,
  HardDrive,
  Shield,
  Settings,
  Mail,
  Lock,
  Eye,
  Activity,
  Box,
  Cpu,
  Cloud,
  Layers,
  Search,
  CheckCircle,
  AlertCircle,
  HelpCircle,
  Compass,
  GitBranch,
  Home,
  Lightbulb,
  Radar,
  ShieldCheck,
  Sparkles,
  Terminal,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  bell: Bell,
  server: Server,
  users: Users,
  database: Database,
  globe: Globe,
  drive: HardDrive,
  shield: Shield,
  settings: Settings,
  mail: Mail,
  lock: Lock,
  eye: Eye,
  activity: Activity,
  box: Box,
  cpu: Cpu,
  cloud: Cloud,
  layers: Layers,
  search: Search,
  check: CheckCircle,
  alert: AlertCircle,
  help: HelpCircle,
  explore: Compass,
  lineage: GitBranch,
  home: Home,
  insights: Lightbulb,
  observability: Radar,
  govern: ShieldCheck,
  domains: Sparkles,
  terminal: Terminal,
};

export function getIcon(iconName: string): LucideIcon {
  const normalizedIcon = iconName.toLowerCase().replace(/[-_]/g, "");
  return iconMap[normalizedIcon] || Settings;
}
